#!/bin/bash
clear
echo -e "\e[36m    ____              __ __                 __  ____  _____\e[0m"
echo -e "\e[36m   / __ \__  __ __  __/ // /_  ____ _____  / /_/ __ \/ ___/\e[0m"
echo -e "\e[36m  / / / / / / / / / / / // /_ / __ \`/ __ \/ __/ / / /\___ \ \e[0m"
echo -e "\e[36m / /_/ / /_/ / /_/ / /__  __// /_/ / / / / /_/ /_/ /___/ / \e[0m"
echo -e "\e[36m/_____/\__,_/\__, /    /_/   \__,_/_/ /_/\__/\____//____/  \e[0m"
echo -e "\e[36m            /____/                                         \e[0m"
echo ""
echo -e "\e[32mOS:\e[0m DuyKhanhOS v6"
echo -e "\e[32mKernel:\e[0m $(uname -r)"
echo -e "\e[32mUptime:\e[0m $(uptime -p)"
echo -e "\e[32mWM:\e[0m DuyKhanhWM"
echo -e "\e[32mShell:\e[0m /bin/bash"
echo ""
read -p "Nhan Enter de bat dau trai nghiem..."
